### Function Example for all Python Data Structures
* List []
* tuple()
* set {}
* dictionart{ : }

## 1 . LIST
* list accepts Duplicate values
* list is one dimentional
* list is heterogenous data structure(ex:accepts int,string,float,etc..,)
* Indexing and slicing is possible
* Accepts Mutable (Mutable-Values once assigned to a variable can be changed inside the list)

#### 1.1 APPEND() - adds the element at the end of the list

In [ ]:
Furnitures=["Chair","Table","Window","Door"]

In [ ]:
type(Furnitures)

list

In [ ]:
Furnitures.append("Sofa")
Furnitures.append("2")
Furnitures

['Chair', 'Table', 'Window', 'Door', 'Sofa', '2']

#### 1.2 CLEAR() - Removes all the elements from the list

In [ ]:
Furnitures.clear()
Furnitures

[]

#### 1.3 COPY() - Returns a copy of the list

In [ ]:
Furnitures=["Chair","Table","Window","Door"]
Furni=Furnitures.copy()
Furni

['Chair', 'Table', 'Window', 'Door']

#### 1.4 EXTEND() - Add the elements of a list (or any iterable), to the end of the current list

In [ ]:
Furnitures.extend("Chair")
Furnitures

['Chair', 'Table', 'Window', 'Door', 'C', 'h', 'a', 'i', 'r']

#### 1.5 INDEX() - Returns the index of the first element with the specified value

In [ ]:
Furnitures=["Chair","Table","Window","Door"]
Furnitures.index("Window")

2

#### 1.6 INSERT() - Adds an element at the specified position

In [ ]:
Furnitures.insert(4,"Bed")
Furnitures

['Chair', 'Table', 'Window', 'Door', 'Bed']

#### 1.7 POP() - Removes the element at the specified position

In [ ]:
Furnitures.pop(-1)
Furnitures

['Chair', 'Table', 'Window', 'Door']

#### 1.8 REMOVE() - Removes the first item with the specified value

In [ ]:
Furnitures.remove("Table")
Furnitures

['Chair', 'Window', 'Door']

#### 1.9 REVERSE() - Reverses the order of the list

In [ ]:
Furnitures.reverse()
Furnitures

['Door', 'Window', 'Chair']

#### 1.10 SORT() - Sorts the list

In [ ]:
Furnitures.sort()
Furnitures

['Chair', 'Door', 'Window']

#### 1.11 count() - Returns the number of elements with the specified value

In [ ]:
Furnitures=["Chair","Table","Window","Door","Chair"]
Furnitures.count("Chair")

2

## 2 . TUPLE
* One Dimentional
* Heterogenous
* Duplicate values is allowed
* indexing and slicing is also posible
* immutable

In [ ]:
Furnitures=("Chair","Table","Window","Door","Door")
Furnitures

('Chair', 'Table', 'Window', 'Door', 'Door')

#### 2.1 TUPLE() Returns the number of times a specified value occurs in a tuple

In [ ]:
Furnitures.count("Door")

2

#### 2.2 COUNT() Searches the tuple for a specified value and returns the position of where it was found

In [ ]:
Furnitures.index("Window")

2

## 3 . SETS
* set is 1 dimenstional
* set is Heterogenous
* set don't allow duplicate values
* Indexing and slicing is not possible
* set is Mutable

In [ ]:
Furnitures={"Chair","Table","Window","Door"}
Furnitures

{'Chair', 'Door', 'Table', 'Window'}

#### 3.1 ADD() - Adds an element to the set

In [ ]:
Furnitures.add("Wood")
Furnitures

{'Chair', 'Door', 'Table', 'Window', 'Wood'}

#### 3.2 CLEAR() - Removes all the elements from the set

In [ ]:
Furnitures.clear()
Furnitures

set()

#### 3.3 COPY() - Returns a copy of the set

In [ ]:
Furnitures={"Chair","Table","Window","Door","Bed"}
f=Furnitures.copy()
f

{'Bed', 'Chair', 'Door', 'Table', 'Window'}

In [ ]:
Furnitures={"Chair","Table","Window","Door"}

#### 3.4 DIFFERENCE() - Returns a set containing the difference between two or more sets

In [ ]:
f.difference(Furnitures)

{'Bed'}

#### 3.5 DIFFERENCE_UPDATE() - Removes the items in this set that are also included in another, specified set

In [ ]:
x={"apple","mango","cherry","banana"}
y={"google","banana","microsoft","apple"}

x.difference_update(y)
print(x)

{'mango', 'cherry'}

#### 3.6 DISCARD() - Remove the specified item

In [ ]:
Furnitures.discard("Bed")
Furnitures

{'Chair', 'Door', 'Table', 'Window'}

#### 3.7 INTERSECTION() - Returns a set, that is the intersection of two other sets

In [ ]:
x={"apple","mango","cherry","banana"}
y={"google","banana","microsoft","apple"}
x.intersection(y)

{'apple', 'banana'}

#### 3.8 INTERSECTION_UPDATE() - Removes the items in this set that are not present in other, specified set(s)

In [ ]:
x={"apple","mango","cherry","banana"}
y={"google","banana","microsoft","apple"}
x.intersection_update(y)
print(x)

{'banana', 'apple'}

#### 3.9 ISDISJOINT() - Returns whether two sets have a intersection or not

In [ ]:
x={"apple","mango","cherry","banana"}
y={"google","banana","microsoft","apple"}
x.isdisjoint(y)

False

In [ ]:
x={"apple","mango","cherry","banana"}
y={"google","microsoft","intel"}
x.isdisjoint(y)

True

#### 3.10 ISSUBSET() - Returns True if all items of this set is present in another set

In [ ]:
x={"apple","mango","cherry","banana"}
y={"google","microsoft","intel"}
x.issubset(y)

False

In [ ]:
x={"apple","mango","cherry","banana"}
y={"apple","mango","cherry","banana"}
x.issubset(y)

True

In [ ]:
x={"apple","mango","cherry"}
y={"apple","mango","cherry","banana"}
x.issubset(y)

True

#### 3.11 ISSUPERSET() - Returns True if all items of another set is present in this set

In [ ]:
x={"apple","mango","cherry",}
y={"apple","mango","cherry"}
x.issuperset(y)

True

In [ ]:
x={"apple","mango","cherry","banana"}
y={"apple","mango","cherry"}
x.issuperset(y)

True

In [ ]:
x={"apple","mango","cherry","banana"}
y={"google","microsoft","intel"}
x.issuperset(y)

False

#### 3.12 POP() - Removes an element from the set

In [ ]:
x={"apple","mango","cherry","banana"}
x.pop()
x

{'apple', 'cherry', 'mango'}

#### 3.13 REMOVE() - Removes the specified element

In [ ]:
x={"apple","mango","cherry","banana"}
x.remove("apple")
x

{'banana', 'cherry', 'mango'}

#### 3.14 SYSMMETRIC_DIFFERENCE() - Returns a set with the symmetric differences of two sets

In [ ]:
x={"apple","mango","cherry","banana"}
x.symmetric_difference("apple")

{'a', 'apple', 'banana', 'cherry', 'e', 'l', 'mango', 'p'}

#### 3.15 SYSMMETRIC_DIFFERENCE_UPDATE() - Inserts the symmetric differences from this set and another

In [ ]:
x={"apple","mango","cherry","banana"}
x.symmetric_difference_update("apple")
x

{'a', 'apple', 'banana', 'cherry', 'e', 'l', 'mango', 'p'}

#### 3.16 UNION() - Return a set containing the union of sets

In [ ]:
x={"apple","mango","cherry","banana"}
y={"google","banana","microsoft","apple"}
x.union(y)

{'apple', 'banana', 'cherry', 'google', 'mango', 'microsoft'}

#### 3.17 UPDATE() - Update the set with the union of this set and others

In [ ]:
x={"apple","mango","cherry","banana"}
y={"google","banana","microsoft","apple"}
x.update(y)
x

{'apple', 'banana', 'cherry', 'google', 'mango', 'microsoft'}

## 4 . DICTIONARY
it is key-value Pair
* two Dimentiona
* heterogenous
* Mutable
* Indexing & Slicing is not possible
* Don't create duplicate key,but you can create duplicate values

#### 4.1 CLEAR() - Removes all the elements from the dictionary

In [ ]:
user_details={"Name":"abdulla","Age":23}
user_details.clear()
user_details

{}

#### 4.2 COPY() - Returns a copy of the dictionary

In [ ]:
user_details={"Name":"abdulla","Age":23}
user_details.copy()
user_details

{'Name': 'abdulla', 'Age': 23}

#### 4.3 FROMKEYS() - Returns a dictionary with the specified keys and value

In [ ]:
user_details={"Name":"abdulla","Age":23}
roll_no=7
user_details.fromkeys(user_details,roll_no)

{'Name': 7, 'Age': 7}

#### 4.4 GET() - Returns the value of the specified key

In [ ]:
user_details={"Name":"abdulla","Age":23}
x=user_details.get("Name")
print(x)

abdulla

#### 4.5 ITEMS() - Returns a list containing a tuple for each key value pair

In [ ]:
user_details={"Name":"abdulla","Age":23}
x=user_details.items()
print(x)

dict_items([('Name', 'abdulla'), ('Age', 23)])

#### 4.6 KEYS() - Returns a list containing the dictionary's keys

In [ ]:
user_details={"Name":"abdulla","Age":23}
x=user_details.keys()
x

dict_keys(['Name', 'Age'])

#### 4.7 POP() - Removes the element with the specified key

In [ ]:
user_details={"Name":"abdulla","Age":23}
x=user_details.pop("Name")
x

'abdulla'

#### 4.8 POPITEM() - Removes the last inserted key-value pair

In [ ]:
user_details={"Name":"abdulla","Age":23}
x=user_details.popitem()
x

('Age', 23)

#### 4.9 SETDEFAULT() - Returns the value of the specified key. If the key does not exist: insert the key, with the specified value

In [ ]:
user_details={"Name":"abdulla","Age":23}
x=user_details.setdefault("Name","Fariq")
x

'abdulla'

#### 4.10 UPDATE() - Updates the dictionary with the specified key-value pairs

In [ ]:
user_details={"Name":"abdulla","Age":23}
user_details.update({"Gender":"Male"})
user_details

{'Name': 'abdulla', 'Age': 23, 'Gender': 'Male'}

#### 4.11 VALUES() - Returns a list of all the values in the dictionary

In [ ]:
user_details={"Name":"abdulla","Age":23,"Gender":"Male"}
user_details.values()

dict_values(['abdulla', 23, 'Male'])

## Creating Two Data-Frames using Pandas

In [ ]:
import pandas as pd

In [ ]:
student_details={"Name":["Fariq","Abdulla","Vivek","Jose","Simon"],
          "Age":[23,24,21,45,34],
          "Place":["Ooty","Kotagiri","Coonoor","Coimbatore","Mettuppalayam"]}

In [ ]:
pd.DataFrame(student_details)

      Name  Age          Place
0    Fariq   23           Ooty
1  Abdulla   24       Kotagiri
2    Vivek   21        Coonoor
3     Jose   45     Coimbatore
4    Simon   34  Mettuppalayam

In [ ]:
student_marks={"Name":["Fariq","Abdulla","Vivek","Jose","Simon"],
                "English":[80,85,65,76,75],
                "Tamil":[78,89,76,54,77],
                "Maths":[90,87,89,76,89],
                "Science":[99,65,98,89,88],
                "S.Science":[87,87,65,78,88]}
pd.DataFrame(student_marks)

      Name  English  Tamil  Maths  Science  S.Science
0    Fariq       80     78     90       99         87
1  Abdulla       85     89     87       65         87
2    Vivek       65     76     89       98         65
3     Jose       76     54     76       89         78
4    Simon       75     77     89       88         88

In [ ]:
patient={"Name":["Ram","Senthil","Kumar","Raman","Steve","Abi"],
         "Age" :[45,56,67,78,76,56],
         "Nationality":["India","Brazil","Potugese","India","America","UAE"],
         "Disease":["Head Ache","Tuberculosis","Fever","Astuma","Bone Fracture","Fever"]}

In [ ]:
pd.DataFrame(patient)

      Name  Age Nationality        Disease
0      Ram   45       India      Head Ache
1  Senthil   56      Brazil   Tuberculosis
2    Kumar   67    Potugese          Fever
3    Raman   78       India         Astuma
4    Steve   76     America  Bone Fracture
5      Abi   56         UAE          Fever